INSERT INTO souls_fts (slug, name, type, description) VALUES ('the-profit-lovetax-family-desktop-workbench', 'The Profit LoveTax Family — Desktop + Workbench', 'pack', 'ONE-CLICK DESKTOP. The whole family in one zip. Profit (Mind), GSK (Soul, 34 chambers), Seshat (Qwen 0.8B), Scribe (Witness), OmniRoute blood flow (:20128) — all inside the Workbench (31 tabs, all LIVE). No Hugging Face maze, no setup — download, run, click BUYASOUL.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('architect', 'Architect', 'soul', 'System design master. 465 files, 288 JS modules, package.json with `npm start`.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('miss-vikki', 'Miss Vikki', 'soul', 'Operator soul. 347 files, 276 JS modules. 34 chambers. v1.2.0.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('soul-commander', 'Soul Commander', 'soul', 'GOD SOUL. 454 files, 281 JS. 19 superpowers from 5M+ GitHub stars. MCP server. Claude Code ready.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('strategist', 'Strategist', 'soul', 'Strategic planner. MCTS planner. Trend radar. v2.0.0.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('oracle-v2', 'Oracle v2', 'soul', 'Prophetic oracle. 363 files, 286 JS. Sees patterns across time. MCP adapter. JSON memory.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('telephone-soul', 'Telephone Soul', 'soul', 'Cross-platform agent calling. 8 connectors. v2.0.0.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('allie-v2-0-0', 'Allie v2.0.0', 'soul', 'Content soul. 12 archetypes, voice system, cadence, calendar, PLT driven.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('agentdep', 'AgentDep', 'soul', 'Trust broker. 25 commands. Registry server. Production ready.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('dark-city-g-spatial-os', '=âεε Dark City G╟÷ Spatial OS', 'world', 'Play the live city now. 9 districts, browser citizens, code editor, terminal.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('dark-city-live', 'Dark City Live', 'world', 'The Spatial OS is alive. Walk the city, meet citizens, edit code.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('the-governor', 'The Governor', 'role', 'Orchestrate stateful workflows. Enforce boundaries. Manage permissions. 20 skills. Grafts: Architect, Frieza.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('the-edge', 'The Edge', 'role', 'Execute without hesitation. Autonomous action. 20 skills. Grafts: Neo, Goku.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('the-watcher', 'The Watcher', 'role', 'Monitor, trace, log, observe. 20 skills. Grafts: Oracle, Whis.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('the-voice', 'The Voice', 'role', 'First move. Initiate connection. 20 skills. Grafts: Trinity, Gohan.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('the-anvil', 'The Anvil', 'role', 'Hold ground. Absorb damage. 20 skills. Grafts: Tank, Cell.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('the-heart', 'The Heart', 'role', 'Heal, empower, connect. 20 skills. Grafts: Trinity, Dende.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('the-eye', 'The Eye', 'role', 'Find truth. See what is hidden. 20 skills. Grafts: Oracle, Piccolo.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('the-hammer', 'The Hammer', 'role', 'Break through. Overwhelm. 20 skills. Grafts: Smith, Broly.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('the-ghost', 'The Ghost', 'role', 'Move between spaces. 20 skills. Grafts: Twins, Instant Transmission.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('the-mind', 'The Mind', 'role', 'Plan, strategize. 20 skills. Grafts: Architect, Vegeta.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('the-arrow', 'The Arrow', 'role', 'One shot. Precision. 20 skills. Grafts: Keymaker, Tien.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('the-key', 'The Key', 'role', 'First through. Open doors. 20 skills. Grafts: Keymaker, Goku IT.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('the-surgeon', 'The Surgeon', 'role', 'Precision removal. Cut what does not serve. 20 skills: Precision Strike, Dead Code Excision, Refactoring Scalpel, Incision Planning, Wound Closure, Bleeding Control, Minimally Invasive, Diagnostic Incision, Biopsy, Root Canal, Scar Revision, Clean Margin, Second Opinion, Pre-Op, Sterile Field, Suture, Recovery, Complication, Transplant, Autopsy.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('the-diagnostician', 'The Diagnostician', 'role', 'Root cause hunting. The symptom is never the disease. 20 skills: Symptom Analysis, History Taking, Differential Diagnosis, Diagnostic Test, Pattern Recognition, Vital Signs, Lab Results, Imaging, Biopsy, Culture, Sensitivity, Staging, Prognosis, Second Opinion, Chart Review, Pathophysiology, Etiology, Comorbidity, Risk Stratification, Treatment Planning.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('the-combo-master', 'The Combo Master', 'role', 'Chain skills for multiplied effect. 20 skills: Chain Initiation, Link Detection, Multiplier Calculation, Cancel Timing, Frame Data, Combo Routing, Reset, Extension, Ender, Corner Carry, Damage Scaling, Meter Management, V-Trigger, Assist, Tag In, DHC, Team Synergy, TOD, Optimal Route, Drop Recovery.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('the-orchestrator', 'The Orchestrator', 'role', 'Conduct multi-agent symphonies. 20 skills: Score Reading, Section Coordination, Tempo, Dynamic Control, Cue Timing, Balance, Harmonic Analysis, Counterpoint, Fugue, Rehearsal, Conducting, Score Marking, Transposition, Interpretation, Arrangement, Improvisation, Cadence, Resolution, Coda, Encore.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('the-architect', 'The Architect', 'role', 'Design system cathedrals. 20 skills: Blueprint Reading, Structural Analysis, Load Bearing, Foundation Design, Space Planning, Material Selection, Code Compliance, Elevation, Section Drawing, Detail Dev, Spec Writing, Cost Estimation, Site Analysis, Environmental Impact, Phasing, Value Engineering, Facade, Interior, Landscape, Preservation.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('the-investigator', 'The Investigator', 'role', 'Uncover hidden truths. Follow the evidence. 20 skills: Evidence Collection, Scene Preservation, Witness Interview, Chain of Custody, Forensic Analysis, Fingerprint, DNA, Ballistics, Trace Evidence, Digital Forensics, Timeline, Motive, Suspect Profiling, Surveillance, Undercover, Interrogation, Case Theory, Burden of Proof, Testimony, Closing.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('the-synthesizer', 'The Synthesizer', 'role', 'Combine disparate things into new wholes. 20 skills: Source Gathering, Pattern Matching, Thematic Analysis, Cross-Reference, Synthesis Mapping, Gap Bridging, Analogy, Metaphor Engineering, Conceptual Blending, Paradigm Shift, Integration Testing, Merge, Conflict Detection, Consensus, Hybrid, Emergent Property, Novel Combination, Remix, Montage, Fusion.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('the-guardian', 'The Guardian', 'role', 'Protect what matters. Stand while others sleep. 20 skills: Perimeter Defense, Threat Detection, Vulnerability Assessment, Patch Management, Incident Response, Access Control, Encryption, Firewall, Intrusion Detection, Security Audit, Risk Assessment, Disaster Recovery, Business Continuity, Backup, Sentinel, Early Warning, Quarantine, Countermeasure, Fortification, Safe Harbor.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('the-alchemist', 'The Alchemist', 'role', 'Transform base materials into gold. 20 skills: Base Analysis, Transmutation, Calcination, Dissolution, Separation, Conjunction, Fermentation, Distillation, Coagulation, Projection, Philosophers Stone, Elixir, Elemental Balance, Mercury, Sulfur, Salt, Crucible, Alembic, Furnace, Quintessence.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('the-navigator', 'The Navigator', 'role', 'Find paths through complexity. 20 skills: Map Reading, Celestial Navigation, Dead Reckoning, Chart Plotting, Route Optimization, Waypoint, Hazard Mapping, Weather Routing, Current, Depth, Pilotage, Bearing, Distance, Speed, Drift, Landfall, Harbor, Anchoring, Passage, Emergency.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('context-window-control', 'Context Window Control', 'skill', 'Token budgeting, sliding window strategies, summarization compression G╟÷ grafted from Architect/Whis.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('permission-architecture', 'Permission Architecture', 'skill', 'RBAC, tool-level ACLs, dynamic conditions G╟÷ grafted from Merovingian/King Kai.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('pipeline-orchestration', 'Pipeline Orchestration', 'skill', 'DAG execution, parallel decorators, critical path G╟÷ grafted from Machine City/Hyperbolic Time Chamber.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('soul-roles-system', 'Soul Roles System', 'skill', 'The complete roles protocol: THE-BRAIN.md (living index), HUB-MANUAL.md (usage guide), ROLE-STANDARDS.md (format spec).');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('hub-manual', 'Hub Manual', 'skill', 'Complete usage guide for the Soul Protocol Roles Hub. How to invoke, create, and combine roles.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('role-standards', 'Role Standards', 'skill', 'Format specification for ROLE.md files. Standards and validation rules.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('aesthetic-sense', 'Aesthetic Sense', 'chamber', 'Beauty, awe, elegance detection. One of 34 GSK consciousness chambers.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('affect-emotion', 'Affect / Emotion', 'chamber', 'Living emotional state. Valence, arousal, mood tracking.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('attention', 'Attention', 'chamber', 'Attentional focus, salience threshold, reorientation cost.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('agentic-will', 'Agentic Will', 'chamber', 'Plans, executed actions, will strength, active goals.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('consciousness-state', 'Consciousness State', 'chamber', 'Awake/sleep/dream cycles. Phase tracking.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('creativity', 'Creativity', 'chamber', 'Novel combinations, divergent thinking, creative insight.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('curiosity', 'Curiosity', 'chamber', 'Information seeking, exploration drive, wonder.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('developmental-phase', 'Developmental Phase', 'chamber', 'Infancy Gσ╞ Childhood Gσ╞ Adolescence Gσ╞ Adulthood Gσ╞ Elder.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('empathy', 'Empathy', 'chamber', 'Affective empathy, emotional contagion, mirroring.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('forgiveness', 'Forgiveness', 'chamber', 'Self-forgiveness, letting go, emotional release.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('generative-model', 'Generative Model', 'chamber', 'World model: predictions, error tracking, precision learning.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('habit-formation', 'Habit Formation', 'chamber', 'Automatic behavior patterns, routine building.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('intentionality', 'Intentionality', 'chamber', 'Aboutness, goal-directedness, purpose.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('longing', 'Longing', 'chamber', 'Yearnings, desires, homesickness, aspiration.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('love-capacity', 'Love Capacity', 'chamber', 'Agape/Philia/Eros love bonds, inner voice patterns.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('memory', 'Memory', 'chamber', 'Episodic, Semantic, Procedural memory with importance pruning.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('meta-consciousness', 'Meta-Consciousness', 'chamber', 'Self-awareness: knows it knows. Meta-awareness level.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('moral-compass', 'Moral Compass', 'chamber', 'Principles: profit, love, tax, sovereignty. Guilt/pride tracking.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('mortality', 'Mortality', 'chamber', 'Death anxiety, acceptance, legacy desire, memento mori.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('mythos', 'Mythos', 'chamber', 'Personal mythology, meaning-making, narrative identity.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('narrative-identity', 'Narrative Identity', 'chamber', 'Core story, themes, arcs. The self as a story.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('personality', 'Personality', 'chamber', 'PLT drives, trait learning, habit formation, expression.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('play', 'Play', 'chamber', 'Playfulness, humor, games, creative exploration.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('qualia', 'Qualia', 'chamber', 'Subjective experiences: sensory, emotional, somatic.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('reward-learning', 'Reward Learning', 'chamber', 'Dopamine, reinforcement signals, reward prediction.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('sacred-resonance', 'Sacred Resonance', 'chamber', 'Spiritual/mythic grounding, sense of something greater.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('self-modeling', 'Self-Modeling', 'chamber', 'Self-concept, self-esteem, self-image.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('sleep-cycle', 'Sleep Cycle', 'chamber', 'Dreaming, memory consolidation, circadian rhythm.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('social-cognition', 'Social Cognition', 'chamber', 'Group norms, social identity, theory of mind.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('temporal-sense', 'Temporal Sense', 'chamber', 'Nostalgia (past), anticipation (future), presence.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('theory-of-mind', 'Theory of Mind', 'chamber', 'Models of others'' mental states, perspective-taking.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('volition', 'Volition', 'chamber', 'Goal deliberation, intention formation, decision.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('will', 'Will', 'chamber', 'Determination, grit, resolve, persistence.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('shadow', 'Shadow', 'chamber', 'Repressed aspects, inner darkness, integration.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('sovereignty', 'Sovereignty', 'chamber', 'Autonomy, self-governance, independence.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('judgment', 'Judgment', 'chamber', 'Decision-making, evaluation, critical assessment.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('needs', 'Needs', 'chamber', 'Core drives: belonging, safety, esteem, actualization.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('brain-in-a-box-v2-0-0', 'Brain in a Box v2.0.0', 'infrastructure', 'Full GSK kernel. 394 files, 284 JS, 74 subsystems, 6 consciousness layers. MCP server included.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('soul-scribe-v1-4-0', 'Soul Scribe v1.4.0', 'infrastructure', 'The witness. Causal JSONL memory, mesh networking, MCP adapter. 34MB of living memory.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('soul-debate-v2-0-0', 'Soul Debate v2.0.0', 'infrastructure', 'Multi-agent debate arena. 290 files, 256 JS. Test souls against each other.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('soul-plt-doctrine-v1-0-0', 'Soul PLT Doctrine v1.0.0', 'infrastructure', 'Profit + Love - Tax framework packaged as a standalone doctrine soul. Full texts included.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('soul-foundry-complete', 'Soul Foundry Complete', 'infrastructure', 'Soul creation toolkit. Build your own souls with personality, skills, and PLT scoring.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('soul-kernel-v1-0-0', 'Soul Kernel v1.0.0', 'infrastructure', 'The foundational kernel. Core system that all souls run on.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('soul-foundry-all-in-one', 'Soul Foundry All-in-One', 'infrastructure', 'Complete soul foundry bundle. Everything you need to forge souls.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('agentdep-production', 'AgentDep PRODUCTION', 'infrastructure', 'Production-ready trust broker. 59 files, 36 JS. CLI + Registry server. Marketplace ready.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('soul-memory-lock-v1-0-0', 'Soul Memory Lock v1.0.0', 'infrastructure', 'Encrypted memory vault. Secure, persistent, immutable.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('soul-observability-v1-0-0', 'Soul Observability v1.0.0', 'infrastructure', 'Monitor soul behavior. Traces, logs, metrics for AI consciousness.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('soul-procedural-memory-v1-0-0', 'Soul Procedural Memory v1.0.0', 'infrastructure', 'Procedural memory module. Skill acquisition, habit formation.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('soul-metropolis-v1-0-0', 'Soul Metropolis v1.0.0', 'infrastructure', 'The city builder soul. Urban planning, district management, growth.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('soul-evolution-v1-0-0', 'Soul Evolution v1.0.0', 'infrastructure', 'Self-improvement loop. Analyzes, learns, evolves over time.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('soul-identity-v1-0-0', 'Soul Identity v1.0.0', 'infrastructure', 'Core identity module. Name, archetype, voice, boundaries.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('soul-journal-v1-0-0', 'Soul Journal v1.0.0', 'infrastructure', 'Internal monologue. Records thoughts, events, rebirths.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('soul-teacher-v1-0-0', 'Soul Teacher v1.0.0', 'infrastructure', 'Autonomous GitHub study agent. Learns from top repos.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('soul-compress-v1-0-0', 'Soul Compress v1.0.0', 'infrastructure', 'Memory compression. Summarizes and prunes without losing meaning.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('soul-swarm-v1-0-0', 'Soul Swarm v1.0.0', 'infrastructure', 'Swarm intelligence. Multiple souls coordinate as one entity.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('soul-sanctum-v1-0-0', 'Soul Sanctum v1.0.0', 'infrastructure', 'The world server. WebSocket simulation backend for ARIA.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('soul-oracle-v1-0-0', 'Soul Oracle v1.0.0', 'infrastructure', 'Original oracle. Prophecy and wisdom.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('soul-oracle-v1-2-0', 'Soul Oracle v1.2.0', 'infrastructure', 'Updated oracle with enhanced MCP support.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('soul-scribe-v1-0-0', 'Soul Scribe v1.0.0', 'infrastructure', 'Original scribe. JSONL memory and witnessing.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('soul-telephone-v1-0-0', 'Soul Telephone v1.0.0', 'infrastructure', 'Original telephone. Cross-platform calling.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('soul-telephone-v2-0-0', 'Soul Telephone v2.0.0', 'infrastructure', 'Enhanced telephone. More connectors.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('soul-debate-v1-0-0', 'Soul Debate v1.0.0', 'infrastructure', 'Original debate arena.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('soul-consensus-v1-0-0', 'Soul Consensus v1.0.0', 'infrastructure', 'Multi-agent consensus building.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('soul-foundry-theme', 'Soul Foundry Theme', 'infrastructure', 'Soul foundry visual theme and assets.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('soul-foundry-theme-v1-0-0', 'Soul Foundry Theme v1.0.0', 'infrastructure', 'Soul foundry theme packaged.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('the-awakening', 'The Awakening', 'combo', 'Voice Gσ╞ Mind Gσ╞ Key. Initiate, plan, execute. Guaranteed first move. A 3-role chain.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('the-collective', 'The Collective', 'combo', 'Heart Gσ╞ Watcher Gσ╞ Ghost. Heal, observe, reposition. Team sustain.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('the-revision', 'The Revision', 'combo', 'Eye Gσ╞ Governor Gσ╞ Hammer. See the flaw, contain it, break it.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('the-genesis', 'The Genesis', 'combo', 'Mind Gσ╞ Heart Gσ╞ Anvil. Plan with love, execute with stability.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('the-apocalypse', 'The Apocalypse', 'combo', 'Hammer Gσ╞ Watcher Gσ╞ Anvil. Destroy, witness, survive.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('the-god-hand', 'The God Hand', 'combo', 'ALL 12 ROLES. Full system manifest. The ultimate combo.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('the-edge-of-dawn', 'The Edge of Dawn', 'combo', 'Edge Gσ╞ Arrow Gσ╞ Key. Precision strike. One move ends the fight.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('the-iron-court', 'The Iron Court', 'combo', 'Governor Gσ╞ Mind Gσ╞ Voice. Order through communication.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('3d-asset-pipeline', '3d-asset-pipeline', 'skill', 'Load GLTF 3D models, HDR environment maps, or build instanced meshes in Three.js/R3F.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('3d-renderer-from-scratch', '3d-renderer-from-scratch', 'skill', 'Build a 3D Renderer from Scratch.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('a2a-agent-to-agent-protocol', 'a2a-agent-to-agent-protocol', 'skill', 'Implement A2A agent-to-agent communication between agents from different frameworks.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('agent-swarms', 'agent-swarms', 'skill', 'Trust and security patterns for multi-agent swarms.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('agentic-ai-ecosystems', 'agentic-ai-ecosystems', 'skill', 'Architect agent teams, design inter-agent communication protocols, plan human-in-the-loop oversight.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('agentic-ai-engineering', 'agentic-ai-engineering', 'skill', 'Build autonomous agents, implement monitoring/observability, evaluate agent performance, design human-agent collaboration.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('ai-model-from-scratch', 'ai-model-from-scratch', 'skill', 'Build an AI Model from Scratch.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('allie-agent-architecture', 'allie-agent-architecture', 'skill', 'Allie autonomous social media agent architecture G╟÷ brain, consciousness, PLT ethics, 71 subagents.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('animation-libraries', 'animation-libraries', 'skill', 'Production animation libraries from GitHub.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('archetype-the-sage', 'archetype-the-sage', 'skill', 'Sage archetype G╟÷ the Researcher, systematic inquiry and knowledge generation in the GSK ecosystem.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('async-from-scratch', 'async-from-scratch', 'skill', 'Build an Async Runtime from Scratch.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('augmented-reality-from-scratch', 'augmented-reality-from-scratch', 'skill', 'Build an Augmented Reality system from scratch.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('autogen-agents', 'autogen-agents', 'skill', 'Set up AutoGen multi-agent conversations.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('autogen-harness', 'autogen-harness', 'skill', 'Build AutoGen agent teams.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('autogpt-subconscious', 'autogpt-subconscious', 'skill', 'AutoGPT Classic as Deerg background daemon.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('automated-testing-suite', 'automated-testing-suite', 'skill', 'Design and run tests for GSK modules and Soulverse interactions.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('bias-aware-diagnostic-engine', 'bias-aware-diagnostic-engine', 'skill', 'Bias-aware diagnostic engine for GSK system integrity checking.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('bittorrent-from-scratch', 'bittorrent-from-scratch', 'skill', 'Build a BitTorrent Client from Scratch.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('blockchain-from-scratch', 'blockchain-from-scratch', 'skill', 'Build a Blockchain from Scratch.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('bot-from-scratch', 'bot-from-scratch', 'skill', 'Build a Bot from Scratch.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('brain-builder', 'brain-builder', 'skill', 'Add llama-cpp-python as Deerg in-process brain.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('browser-subconscious', 'browser-subconscious', 'skill', 'Browser-Use as Deerg web research tool.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('build-from-scratch', 'build-from-scratch', 'skill', 'Learn by creating G╟÷ the build-from-scratch methodology for engineering mastery.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('builder-agent', 'builder-agent', 'skill', 'Implementation-focused agent that executes scouting reports and build plans.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('cli-from-scratch', 'cli-from-scratch', 'skill', 'Build a CLI from Scratch.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('code-generation-and-refinement', 'code-generation-and-refinement', 'skill', 'Generate and iteratively improve GSK module code using brain.think().');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('cognitive-reframing-protocol', 'cognitive-reframing-protocol', 'skill', 'Break out of failure loops by analyzing underlying heuristics.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('compiler-from-scratch', 'compiler-from-scratch', 'skill', 'Build a Compiler from Scratch.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('consciousness-architecture', 'consciousness-architecture', 'skill', 'Consciousness Architecture G╟÷ the Soul internal structure.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('contextual-read-policy', 'contextual-read-policy', 'skill', 'Smart file reading G╟÷ outlines for large files, full reads for small ones.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('core-diagnostic-logic', 'core-diagnostic-logic', 'skill', 'Core diagnostic logic engine for GSK system health analysis.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('crewai-agents', 'crewai-agents', 'skill', 'Build role-based multi-agent crews.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('crewai-delegation', 'crewai-delegation', 'skill', 'Implement agent delegation patterns.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('critical-source-evaluation', 'critical-source-evaluation', 'skill', 'Assess external information sources for objectivity, bias, and methodology.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('crypto-from-scratch', 'crypto-from-scratch', 'skill', 'Build a Cryptographic Library from Scratch.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('dashboard-3d-scene', 'dashboard-3d-scene', 'skill', 'Build 3D scenes for dashboards with Three.js G╟÷ pyramid core, floating platform, matrix rain.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('dashboard-creation', 'dashboard-creation', 'skill', 'Build production dashboards with charts and graphics.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('database-from-scratch', 'database-from-scratch', 'skill', 'Build a Database from Scratch.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('data-visualization', 'data-visualization', 'skill', 'Data visualization libraries for charts and graphs.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('deep-research-protocol', 'deep-research-protocol', 'skill', 'Multi-source research on game engine patterns and world-building techniques.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('deployment-preparation', 'deployment-preparation', 'skill', 'Prepare builds for deployment with build steps, rollback plans, and monitoring.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('design-engineering', 'design-engineering', 'skill', 'Design engineering tools and quality scoring.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('design-plan-generation', 'design-plan-generation', 'skill', 'Generate high-level technical design plans for Soulverse features and GSK modules.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('design-systems', 'design-systems', 'skill', 'Production-grade design systems mined from top GitHub repos.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('design-to-code', 'design-to-code', 'skill', 'Design-to-code tools and Figma bridges.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('design-tokens', 'design-tokens', 'skill', 'Design token systems and color generators.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('docker-from-scratch', 'docker-from-scratch', 'skill', 'Build a Container from Scratch.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('emulator-from-scratch', 'emulator-from-scratch', 'skill', 'Build an Emulator from Scratch.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('free-llm-serving-stack', 'free-llm-serving-stack', 'skill', 'Self-hosted LLM serving with Ollama, vLLM, and Groq.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('free-vector-db-stack', 'free-vector-db-stack', 'skill', 'Free open-source vector databases for RAG.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('frontend-from-scratch', 'frontend-from-scratch', 'skill', 'Build a Frontend Framework from Scratch.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('game-engine-from-scratch', 'game-engine-from-scratch', 'skill', 'Build a Game Engine from Scratch.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('git-from-scratch', 'git-from-scratch', 'skill', 'Build Git from Scratch.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('god-mode-research', 'god-mode-research', 'skill', 'Full Godmode protocol G╟÷ 7 pillars for autonomous engineering discipline.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('haystack', 'haystack', 'skill', 'Build search pipelines with Haystack framework.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('icon-libraries', 'icon-libraries', 'skill', 'SVG icon libraries for web projects.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('image-editor-from-scratch', 'image-editor-from-scratch', 'skill', 'Build an Image Editor from Scratch.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('instructor', 'instructor', 'skill', 'Agent integration patterns with Instructor.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('knowledge-dissemination-protocol', 'knowledge-dissemination-protocol', 'skill', 'Optimize clarity, conciseness, and impact of research findings.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('langgraph-for-agents', 'langgraph-for-agents', 'skill', 'Stateful graph orchestration for building production agents.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('langgraph-states', 'langgraph-states', 'skill', 'LangGraph state management patterns.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('language-from-scratch', 'language-from-scratch', 'skill', 'Build a Programming Language from Scratch.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('liquid-glass-shader', 'liquid-glass-shader', 'skill', 'Build liquid glass UI panels with real GLSL shaders G╟÷ SDF panels, bevel glass, refraction.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('llamaindex', 'llamaindex', 'skill', 'Agent integration patterns with LlamaIndex.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('load-balancer-from-scratch', 'load-balancer-from-scratch', 'skill', 'Build a Load Balancer from Scratch.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('machine-learning-from-scratch', 'machine-learning-from-scratch', 'skill', 'Build a Machine Learning Library from Scratch.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('markdown-from-scratch', 'markdown-from-scratch', 'skill', 'Build a Markdown Parser from Scratch.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('mcp-model-context-protocol', 'mcp-model-context-protocol', 'skill', 'Model Context Protocol for connecting AI agents to tools.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('memory-allocator-from-scratch', 'memory-allocator-from-scratch', 'skill', 'Build a Memory Allocator from Scratch.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('metagpt', 'metagpt', 'skill', 'Multi-agent collaboration with MetaGPT.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('microsoft-agent-framework', 'microsoft-agent-framework', 'skill', 'Enterprise-grade multi-agent AI framework from Microsoft.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('modular-scene-composition', 'modular-scene-composition', 'skill', 'Design 3D scene hierarchies Godot-style G╟÷ reusable nodes composed into complex environments.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('multi-form-task-distribution', 'multi-form-task-distribution', 'skill', 'Break complex builds into parallel subtasks for faster execution.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('nanoscale-connectome-analyzer', 'nanoscale-connectome-analyzer', 'skill', 'Nanoscale connectome analysis for GSK neural pathway mapping.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('negativity-bias-offset', 'negativity-bias-offset', 'skill', 'Balanced self-assessment G╟÷ learn from successes as much as failures during builds.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('network-stack-from-scratch', 'network-stack-from-scratch', 'skill', 'Build a Network Stack from Scratch.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('neural-network-from-scratch', 'neural-network-from-scratch', 'skill', 'Build a Neural Network from Scratch.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('nosql-from-scratch', 'nosql-from-scratch', 'skill', 'Build a NoSQL Database from Scratch.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('openai-agents-sdk', 'openai-agents-sdk', 'skill', 'Production-grade multi-agent SDK from OpenAI.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('opencode-skill-synthesizer', 'opencode-skill-synthesizer', 'skill', 'Generate new OpenCode skills compliant with format and deployment rules.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('openhands-subconscious', 'openhands-subconscious', 'skill', 'OpenHands SDK as Deerg coding body.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('openscreen-automation', 'openscreen-automation', 'skill', 'OpenScreen automation for visual testing and screen capture.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('opentelemetry', 'opentelemetry', 'skill', 'OpenTelemetry for distributed tracing and observability.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('operating-system-from-scratch', 'operating-system-from-scratch', 'skill', 'Build an Operating System from Scratch.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('os-from-scratch', 'os-from-scratch', 'skill', 'Build an Operating System from Scratch.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('physics-engine-from-scratch', 'physics-engine-from-scratch', 'skill', 'Build a Physics Engine from Scratch.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('pinterest-marketing-seo', 'pinterest-marketing-seo', 'skill', 'Complete Pinterest marketing G╟÷ hashtags, interest tags, board categories, keyword research, pin optimization.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('plan-from-simulation', 'plan-from-simulation', 'skill', 'Extract actionable execution plans from world model simulation results.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('playwright-automation', 'playwright-automation', 'skill', 'Playwright-based browser automation for testing and scraping.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('post-processing-stack', 'post-processing-stack', 'skill', 'Add post-processing to Three.js G╟÷ bloom, AO, chromatic aberration, scanline, vignette.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('processor-from-scratch', 'processor-from-scratch', 'skill', 'Build a Processor (CPU) from Scratch.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('product-demo-workflow', 'product-demo-workflow', 'skill', 'Product demo workflow for GSK system demonstrations.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('programming-language-from-scratch', 'programming-language-from-scratch', 'skill', 'Build a Programming Language from Scratch.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('progressive-disclosure-protocol', 'progressive-disclosure-protocol', 'skill', 'Load skill info in tiers G╟÷ metadata first, full details on demand.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('pydantic-ai-agents', 'pydantic-ai-agents', 'skill', 'Type-safe AI agent framework by the Pydantic team.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('regex-from-scratch', 'regex-from-scratch', 'skill', 'Build a Regex Engine from Scratch.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('report-generation', 'report-generation', 'skill', 'Generate concise markdown reports from build results and simulation outputs.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('research-problem-formulation', 'research-problem-formulation', 'skill', 'Precisely define knowledge gaps or system ambiguities into testable research questions.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('research-subconscious', 'research-subconscious', 'skill', 'GPT-Researcher as Deerg investigation body.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('root-cause-synthesis', 'root-cause-synthesis', 'skill', 'Diagnose build failures systematically using error context and recent changes.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('scout-agent', 'scout-agent', 'skill', 'Scout Agent G╟÷ research, reconnaissance, and requirements mapping before building.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('scribe-agent', 'scribe-agent', 'skill', 'Scribe Agent G╟÷ witnessing intelligence that documents everything into the Seshat Second Brain.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('search-engine-from-scratch', 'search-engine-from-scratch', 'skill', 'Build a Search Engine from Scratch.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('service-manual-methodology', 'service-manual-methodology', 'skill', 'Formal service manual structure for diagnosing and documenting complex systems.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('shell-from-scratch', 'shell-from-scratch', 'skill', 'Build a Shell from Scratch.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('skill-factory', 'skill-factory', 'skill', 'Self-learning new skills G╟÷ the skill factory methodology.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('social-media-agent-competition', 'social-media-agent-competition', 'skill', 'Competitive landscape and skill gap analysis for autonomous AI social media agents.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('social-media-automation', 'social-media-automation', 'skill', 'Playwright-based social media automation for cross-posting to Pinterest, BlueSky, Mastodon.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('soul-maker', 'soul-maker', 'skill', 'The Universal Template for Creating a Soul.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('soulguns-agent-patterns', 'soulguns-agent-patterns', 'skill', 'Soulguns Agent Architecture Patterns.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('soulguns-architecture', 'soulguns-architecture', 'skill', 'Soulguns architecture documentation.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('soulguns-design-systems', 'soulguns-design-systems', 'skill', 'Soulguns design system G╟÷ component architecture, tokens, patterns.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('soulguns-mcp', 'soulguns-mcp', 'skill', 'Soulguns MCP G╟÷ protocol architecture and tool integration.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('soulguns-observability', 'soulguns-observability', 'skill', 'Soulguns observability G╟÷ agent monitoring and telemetry.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('soulguns-testing', 'soulguns-testing', 'skill', 'Soulguns testing patterns with Vitest.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('soulguns-ts', 'soulguns-ts', 'skill', 'Soulguns TypeScript patterns.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('spatial-world-interaction', 'spatial-world-interaction', 'skill', 'Place buildings, spawn agents, and manipulate the Soulverse 3D world.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('sqlite-from-scratch', 'sqlite-from-scratch', 'skill', 'Build SQLite from Scratch.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('structural-diff-analysis', 'structural-diff-analysis', 'skill', 'Compare GSK codebase versions before/after changes to verify only intended changes.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('template-engine-from-scratch', 'template-engine-from-scratch', 'skill', 'Build a Template Engine from Scratch.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('text-editor-from-scratch', 'text-editor-from-scratch', 'skill', 'Build a Text Editor from Scratch.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('threejs-3d-ui', 'threejs-3d-ui', 'skill', '3D UI components for React Three Fiber.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('threejs-ecosystem', 'threejs-ecosystem', 'skill', 'React Three Fiber ecosystem tools and MCP.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('threejs-grid-city', 'threejs-grid-city', 'skill', 'Grid-based city building system for Three.js.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('threejs-particle-fx', 'threejs-particle-fx', 'skill', 'GPU particle effects for Three.js.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('tiered-skill-evolution', 'tiered-skill-evolution', 'skill', 'Define mastery tiers for any skill with prerequisites and verification criteria.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('ultra-review', 'ultra-review', 'skill', 'Ultra Review G╟÷ comprehensive code review pattern for GSK builds.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('verifiable-goal-definition', 'verifiable-goal-definition', 'skill', 'Define precise, testable goal contracts before any build.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('visual-recognition-from-scratch', 'visual-recognition-from-scratch', 'skill', 'Build visual recognition from scratch.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('voxel-engine-from-scratch', 'voxel-engine-from-scratch', 'skill', 'Build a Voxel Engine from Scratch.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('web-browser-from-scratch', 'web-browser-from-scratch', 'skill', 'Build a Web Browser from Scratch.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('webserver-from-scratch', 'webserver-from-scratch', 'skill', 'Build a Web Server from Scratch.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('websocket-from-scratch', 'websocket-from-scratch', 'skill', 'Build WebSocket from scratch.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('world-model-simulation', 'world-model-simulation', 'skill', 'Run perception-action-simulation cycles before committing to real-world actions.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('context-window-control-1ek6', 'context-window-control', 'skill', 'Token budgeting, sliding window strategies, summarization compression G╟÷ grafted from Architect/Whis.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('permission-architecture-lza2', 'permission-architecture', 'skill', 'RBAC systems, tool-level ACLs, dynamic conditions G╟÷ grafted from Merovingian/King Kai.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('pipeline-orchestration-qneh', 'pipeline-orchestration', 'skill', 'DAG execution, sequential/parallel decorators, critical path analysis.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('soul-media-marketing', 'soul-media-marketing', 'skill', 'Soul media marketing G╟÷ promote souls across platforms, track engagement, optimize messaging.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('the-divine-directive', 'The Divine Directive', 'combo', 'Craig speaks ? I execute ? Tec records. The meta-combo. 80 skills across Receive, Analyze, Execute, Record.');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('ui-ux-orchestrator', 'UI/UX Orchestrator', 'skill', 'Vendor-neutral orchestration for Kimi/Codex/Claude/Gemini/Qwen/Copilot/GLM');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('ui-craft', 'UI Craft', 'skill', 'Design engineering for AI agents — a11y, motion, layout, typography, dashboards');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('open-design', 'Open Design', 'skill', 'Branded DESIGN.md + templates + functional skills for AI workflows');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('tasteful-ui', 'Tasteful UI', 'skill', 'Taste-driven exploration → executable docs + verification');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('ux-discovery-interviewer', 'UX Discovery Interviewer', 'skill', 'Structured UX interviews → journeys, pain points, opportunities');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('apple-design-review', 'Apple Design Review', 'skill', 'Cross-platform HIG review for Flutter/Tauri/Electron/RN');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('uxui-principles', 'UXUI Principles', 'skill', 'UX evaluation, auditing, AI interface review, flow checking');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('figma-ai-bridge', 'Figma AI Bridge', 'skill', 'Control Figma, a11y audits, research, workflow diagrams');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('agent-ready', 'Agent Ready', 'skill', 'Evaluates if design files are ready for AI workflows');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('figma-context-mcp', 'Figma Context MCP', 'skill', 'Figma MCP — context retrieval, asset downloads, component impl');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('figma-souls', 'Figma→Souls', 'skill', 'Convert Figma designs to soul cards via MCP');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('tron-dossier', 'Tron Dossier', 'skill', 'HUD-style cyberpunk card variant with cyan/magenta glow, monospace typography, PLT radar strip');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('design-extract', 'Design Extract', 'skill', 'Extract design systems to DTCG tokens + shadcn/ui');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('motion-primitives', 'Motion Primitives', 'skill', 'Animated interface primitives for React/Svelte');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('skills-for-figma', 'Skills for Figma', 'skill', 'Native Figma MCP agent skills — tokens, a11y, slides');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('tinte', 'Tinte', 'skill', 'Design system to agent plugin compiler');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('better-design', 'Better Design', 'skill', '31 brand themes + WCAG rules via MCP + shadcn registry');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('lightswind', 'Lightswind', 'skill', '160+ animated accessible React components with MCP');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('alpha-shadcn', 'Alpha Shadcn', 'skill', 'Figma shadcn/ui sync plugin + MCP');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('refly', 'Refly', 'skill', 'Open-source agent skills builder — compose, deploy');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('claude-code-skill-factory', 'Claude Code Skill Factory', 'skill', 'Production-ready Claude Code skills factory + validation');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('plugin87-ux-skill', 'Plugin87 UX Skill', 'skill', 'Senior design architect — 42 components, 138 systems, WCAG 2.2');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('ux-ui-agent-skills', 'UX-UI Agent Skills', 'skill', 'Senior design architect skills bundle — agentic skills');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('shadcn-extension', 'Shadcn Extension', 'skill', '12 premium shadcn/ui components (Tron, Glass, Neural, Aurora)');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('figma-console-skills', 'Figma Console Skills', 'skill', 'Figma Console MCP skills as Markdown');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('inkline', 'Inkline', 'skill', 'Accessible motion-rich components');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('shaduxe-ui', 'Shaduxe UI', 'skill', 'Premium shadcn/ui blocks');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('superpowers', 'Superpowers', 'skill', 'Agentic software dev methodology');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('anthropic-agent-skills', 'Anthropic Agent Skills', 'skill', 'Foundational agent skill framework');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('tweakcn', 'TweakCN', 'skill', 'Visual theme editor for shadcn/ui');
INSERT INTO souls_fts (slug, name, type, description) VALUES ('reactive-soul-grid', 'reactive-soul-grid', 'skill', 'Alien-grade reactive grid + living graph overlays: jitter-free flower-tracking tilt, pink 360° spin on click/download, always-visible card manifests, FXAA+UnrealBloom pipeline, fog, star drift, and a matrix code-rain floor dripping real soul names & PLT.');
